version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt

      # Setup SSH
      - mkdir -p ~/.ssh
      - printf "%s" "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keygen -l -f ~/.ssh/id_rsa

      # Add EC2 host
      - ssh-keyscan -H 16.112.18.209 >> ~/.ssh/known_hosts

  build:
    commands:
      - echo Build started...
      - python -m py_compile app.py

  post_build:
    commands:
      - echo Deployment started...
      - ssh -v ec2-user@16.112.18.209 'cd /home/ec2-user/flask-cicd-project && git pull'

artifacts:
  files:
    - '**/*'